<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;
/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends \Doctrine\ORM\EntityRepository
{

    public function myFindMails($id)
    {
        $query = $this->_em->createQuery('SELECT a.email FROM AppBundle:Auteur a WHERE a.id = :id');
        $query->setParameter('id', $id);

        return $query->getResult();
    }
    public function myFindTextes($id)
    {
        $query = $this->_em->createQuery('SELECT a.texte FROM AppBundle:Auteur a WHERE a.id = :id');
        $query->setParameter('id', $id);

        return $query->getResult();
    }

}
