<?php

namespace AppBundle\Repository;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends \Doctrine\ORM\EntityRepository
{

    public function myFindMails($id)
    {
        $query = $this->_em->createQuery('SELECT emails FROM AppBundle:Auteur a WHERE a.id = ;id');
        $query->setParameter('id', $id);

        return $query->getResult();
    }

}
