site_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
site_firstline:
    path:     /New
    defaults: { _controller: AppBundle:Default:firstline }
site_register:
    path:     /New/{id}
    defaults: { _controller: AppBundle:Default:newline }
    requirements:
      id: \d+
site_envoi:
    path:     /Send/{id}
    defaults: { _controller: AppBundle:Default:send }
    requirements:
      id: \d+
site_story:
    path:     /Show/{id}
    defaults: { _controller: AppBundle:Default:show }
    requirements:
      id: \d+
site_storyView:
    path:     /All
    defaults: { _controller: AppBundle:Default:storyView }
