site_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
site_register:
    path:     /New/{id}
    defaults: { _controller: AppBundle:Default:newline }
    requirements:
      id: \d+
